FROM phpdockerio/php72-fpm:latest

RUN apt-get update \
    && apt-get -y install curl \
    git \
    php7.2-memcached \
    php7.2-mysql \
    php7.2-redis \
    php7.2-gd \
    php7.2-imagick \
    php7.2-intl \
    php7.2-xdebug \
    php7.2-mbstring

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
